title: "Kubernetes pods logs"
type: logs
streams:
  - input: logfile
    title: Collect Kubernetes pods logs
    description: Collect Kubernetes pods logs
    vars:
      - name: paths
        type: text
        required: true
        title: Kubernetes pods log path
        multi: true
        default:
          - /var/log/containers/*${kubernetes.container.id}.log
      - name: symlinks
        type: bool
        title: Use Symlinks
        multi: false
        required: true
        show_user: true
        default: true
