title: "Kubernetes pod logs"
type: logs
streams:
  - input: logfile
    title: Collect Kubernetes pod logs
    description: Collect Kubernetes pod logs
    vars:
      - name: paths
        type: text
        required: true
        title: Kubernetes pod log path
        multi: true
        default:
          - /var/log/containers/*${kubernetes.container.id}.log
      - name: symlinks
        type: bool
        title: Use Symlinks
        multi: false
        required: true
        show_user: true
        default: true
